project:
  name: Precinct Impacts of Redistricting (PIoR) 
  description: >
    Database, mapping tools, and analysis to quantify impact on precinct-level composition after redistricting.
    Scope is initially motivated by Texas redistricting. May be expanded to other states in the future. 
  tools:
    - "python"
    - "GIS"
  current_focus: "Scraping relevant base dataset" 
  needs: []
  links:
    docs: ''
    staging: ''
    production: ''
  team:
    lead: ''
    contributors: []
  campaign:
    candidate: Bluebonnet Internal
    office: State Infrastructure
  auto_refresh: true
